"""Incident report output.

Gradio main page uses an iframe (data: URL) so the colorful/dark HTML keeps its colors.
"""

from __future__ import annotations

import base64
import html
import json
import uuid
from datetime import datetime, timezone
from typing import Optional

from blamebug.models import IncidentAnalysis, Severity


def _esc(s: str) -> str:
    return html.escape(s, quote=True)


def json_dumps_safe(obj: dict) -> str:
    try:
        return json.dumps(obj, default=str)[:2000]
    except Exception:
        return "{}"


def build_report_text(
    analysis: IncidentAnalysis,
    raw_logs: str,
    *,
    report_id: Optional[str] = None,
    source: Optional[str] = None,
    metadata: Optional[dict] = None,
) -> str:
    """
    Plain-text report for Gradio (gr.Textbox). No HTML — avoids Gradio's .prose wrapper
    and theme/CSS issues entirely.
    """
    rid = report_id or str(uuid.uuid4())
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    comps = ", ".join(analysis.affected_components) if analysis.affected_components else "—"
    log_preview = raw_logs.strip()
    if len(log_preview) > 8000:
        log_preview = log_preview[:8000] + "\n… [truncated]"

    lines = [
        "══════════════════════════════════════════════════════════════",
        "BLAMEBUG INCIDENT REPORT",
        "══════════════════════════════════════════════════════════════",
        f"Severity : {analysis.severity.value.upper()}",
        f"Title    : {analysis.title}",
        f"Report ID: {rid}",
        f"Time     : {ts}",
        "",
        "──────────────────────────────────────────────────────────────",
        "EXECUTIVE SUMMARY",
        "──────────────────────────────────────────────────────────────",
        analysis.summary,
        "",
        "──────────────────────────────────────────────────────────────",
        "IMPACT",
        "──────────────────────────────────────────────────────────────",
        analysis.impact_assessment,
        f"Affected components: {comps}",
        "",
        "──────────────────────────────────────────────────────────────",
        "ROOT CAUSE (HYPOTHESIS)",
        "──────────────────────────────────────────────────────────────",
        analysis.root_cause_hypothesis,
        f"Confidence: {analysis.confidence:.0%} — verify before acting.",
        "",
        "──────────────────────────────────────────────────────────────",
        "IMMEDIATE ACTIONS",
        "──────────────────────────────────────────────────────────────",
    ]
    for i, step in enumerate(analysis.immediate_actions, 1):
        lines.append(f"{i}. {step}")
    lines.extend(
        [
            "",
            "──────────────────────────────────────────────────────────────",
            "LONG-TERM REMEDIATION",
            "──────────────────────────────────────────────────────────────",
        ]
    )
    for i, step in enumerate(analysis.long_term_remediation, 1):
        lines.append(f"{i}. {step}")
    lines.extend(
        [
            "",
            "──────────────────────────────────────────────────────────────",
            "RAW LOGS",
            "──────────────────────────────────────────────────────────────",
        ]
    )
    if source:
        lines.append(f"Source: {source}")
    if metadata:
        lines.append(f"Metadata: {json_dumps_safe(metadata)}")
    lines.append(log_preview)
    lines.extend(
        [
            "",
            "──────────────────────────────────────────────────────────────",
            "Generated by BlameBug — automated incident analysis.",
        ]
    )
    return "\n".join(lines)


def build_report_html(
    analysis: IncidentAnalysis,
    raw_logs: str,
    *,
    report_id: Optional[str] = None,
    source: Optional[str] = None,
    metadata: Optional[dict] = None,
) -> str:
    """Standalone colorful/dark HTML for /api/reports/{report_id}."""
    rid = report_id or str(uuid.uuid4())
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    sev = analysis.severity.value
    pal = {
        "critical": {"accent": "#ef4444", "banner": "#7f1d1d", "wash": "rgba(127,29,29,0.45)"},
        "high": {"accent": "#f97316", "banner": "#9a3412", "wash": "rgba(154,52,18,0.40)"},
        "medium": {"accent": "#eab308", "banner": "#854d0e", "wash": "rgba(133,77,14,0.35)"},
        "low": {"accent": "#3b82f6", "banner": "#1e3a5f", "wash": "rgba(30,58,95,0.35)"},
        "info": {"accent": "#22c55e", "banner": "#14532d", "wash": "rgba(20,83,45,0.35)"},
    }.get(sev, {"accent": "#eab308", "banner": "#854d0e", "wash": "rgba(133,77,14,0.35)"})

    comps = ", ".join(analysis.affected_components) if analysis.affected_components else "—"
    log_preview = raw_logs.strip()
    if len(log_preview) > 8000:
        log_preview = log_preview[:8000] + "\n… [truncated]"

    meta_bits = []
    if source:
        meta_bits.append(f"<span class='meta'>Source: {_esc(source)}</span>")
    if metadata:
        meta_bits.append(
            f"<span class='meta'>Metadata: {_esc(json_dumps_safe(metadata))}</span>"
        )
    meta_html = "".join(meta_bits)

    actions = "".join(f"<li>{_esc(x)}</li>" for x in analysis.immediate_actions)
    longterm = "".join(
        f"<li>{_esc(x)}</li>" for x in analysis.long_term_remediation
    )

    title = _esc(analysis.title)
    badge = _esc(sev.upper())

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>BlameBug — {title}</title>
  <style>
    :root {{
      --bg: #0b1220;
      --card: rgba(17,24,39,0.80);
      --card-2: rgba(15,23,42,0.78);
      --text: #e5e7eb;
      --muted: #94a3b8;
      --border: rgba(148,163,184,0.18);
      --heading: #f8fafc;
      --shadow: 0 10px 30px rgba(0,0,0,0.25);
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
      background:
        radial-gradient(1200px 800px at 20% 10%, {pal["wash"]}, transparent 60%),
        radial-gradient(1000px 600px at 80% 0%, rgba(34,197,94,0.06), transparent 55%),
        var(--bg);
      color: var(--text);
      line-height: 1.55;
    }}
    .wrap {{
      max-width: 980px;
      margin: 0 auto;
      padding: 18px 14px 44px;
    }}
    .banner {{
      border-radius: 14px;
      padding: 16px 18px;
      margin-bottom: 14px;
      background: linear-gradient(90deg, {pal["banner"]} 0%, rgba(0,0,0,0) 100%);
      border: 1px solid rgba(255,255,255,0.10);
      box-shadow: var(--shadow);
      overflow: hidden;
      position: relative;
    }}
    .banner::after {{
      content: "";
      position: absolute;
      inset: 0;
      background: radial-gradient(650px 200px at 20% 0%, {pal["accent"]}40, transparent 60%);
      pointer-events: none;
    }}
    .bannerTop {{
      position: relative;
      z-index: 1;
      display: flex;
      flex-wrap: wrap;
      gap: 10px 12px;
      align-items: center;
    }}
    .badge {{
      display: inline-flex;
      align-items: center;
      padding: 6px 10px;
      border-radius: 999px;
      background: {pal["accent"]};
      color: #fff;
      font-weight: 900;
      letter-spacing: 0.06em;
      font-size: 11px;
      text-transform: uppercase;
    }}
    .title {{
      font-size: 22px;
      font-weight: 900;
      color: var(--heading);
      margin: 0;
      letter-spacing: -0.02em;
    }}
    .sub {{
      position: relative;
      z-index: 1;
      margin-top: 8px;
      color: var(--muted);
      font-size: 12.5px;
    }}
    code {{
      background: rgba(255,255,255,0.06);
      border: 1px solid rgba(255,255,255,0.10);
      padding: 2px 7px;
      border-radius: 8px;
      color: #e2e8f0;
    }}
    .grid {{
      display: grid;
      grid-template-columns: 1fr;
      gap: 12px;
      margin-top: 10px;
    }}
    .card {{
      background: var(--card);
      border: 1px solid var(--border);
      border-radius: 14px;
      padding: 16px 18px;
      box-shadow: 0 8px 22px rgba(0,0,0,0.20);
      overflow: hidden;
    }}
    .card h2 {{
      margin: 0 0 10px;
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 0.10em;
      color: rgba(226,232,240,0.92);
      font-weight: 800;
    }}
    .card p {{
      margin: 0;
      white-space: pre-wrap;
      color: #f1f5f9;
      font-size: 15px;
    }}
    .metaRow {{
      margin: 8px 0 10px;
      display: flex;
      flex-wrap: wrap;
      gap: 8px 12px;
    }}
    .meta {{
      color: var(--muted);
      font-size: 12.5px;
      padding: 4px 10px;
      border-radius: 999px;
      border: 1px solid rgba(148,163,184,0.18);
      background: rgba(148,163,184,0.06);
    }}
    ol {{
      margin: 8px 0 0 18px;
      padding: 0;
      color: #f1f5f9;
    }}
    li {{
      margin: 8px 0;
      font-size: 15px;
    }}
    pre.raw {{
      margin: 10px 0 0;
      background: rgba(2,6,23,0.65);
      border: 1px solid rgba(148,163,184,0.18);
      border-radius: 12px;
      padding: 14px 14px;
      color: #cbd5e1;
      overflow-x: auto;
      font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
      font-size: 13px;
      white-space: pre-wrap;
      word-break: break-word;
      line-height: 1.45;
    }}
    .foot {{
      margin-top: 18px;
      color: var(--muted);
      font-size: 12px;
      text-align: center;
    }}
  </style>
</head>
<body>
  <div class="wrap">
    <div class="banner">
      <div class="bannerTop">
        <span class="badge">{badge}</span>
        <h1 class="title">{title}</h1>
      </div>
      <div class="sub">
        Report <code>{_esc(rid)}</code> · {ts}
      </div>
    </div>

    <div class="grid">
      <div class="card">
        <h2>Executive summary</h2>
        <p>{_esc(analysis.summary)}</p>
      </div>

      <div class="card">
        <h2>Impact</h2>
        <p>{_esc(analysis.impact_assessment)}</p>
        <p style="margin-top:10px;color:var(--muted);font-size:14px">
          Affected components: <strong style="color:#e2e8f0">{_esc(comps)}</strong>
        </p>
      </div>

      <div class="card">
        <h2>Root cause (hypothesis)</h2>
        <p>{_esc(analysis.root_cause_hypothesis)}</p>
        <p style="margin-top:10px;color:var(--muted);font-size:14px">
          Confidence: {analysis.confidence:.0%} — treat as hypothesis until verified.
        </p>
      </div>

      <div class="card">
        <h2>Immediate actions</h2>
        <ol>{actions}</ol>
      </div>

      <div class="card">
        <h2>Long-term remediation</h2>
        <ol>{longterm}</ol>
      </div>

      <div class="card">
        <h2>Raw logs</h2>
        <div class="metaRow">{meta_html}</div>
        <pre class="raw">{_esc(log_preview)}</pre>
      </div>
    </div>

    <div class="foot">Generated by BlameBug — automated incident analysis.</div>
  </div>
</body>
</html>"""


def gradio_html_iframe(full_document: str) -> str:
    """Wrap full HTML in an iframe so Gradio theme CSS can't recolor it."""
    b64 = base64.b64encode(full_document.encode("utf-8")).decode("ascii")
    return (
        '<iframe title="BlameBug report" '
        f'src="data:text/html;charset=utf-8;base64,{b64}" '
        'style="width:100%;min-height:620px;border:1px solid #e5e7eb;'
        'border-radius:10px;overflow:hidden;background:#0b1220;'
        'box-sizing:border-box;"></iframe>'
    )
